version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "9000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
