version: '3.8'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: claudiu
      POSTGRES_PASSWORD: parolaSuperSigura
      POSTGRES_DB: todo_db
    ports:
      - "9000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
